### ISSUE TITLE
第15题：描述下Css中的常用布局

### ISSUE THREAD

**Issue by hezhengjie** [Libra-studio/One-question-every-week#15]

**Comment by hezhengjie** [comment]
## 居中布局

### 水平居中

- display:inline或者display: inline-block的行内元素,使用**`text-align`**

```css
.parent {
    text-align: center;
}
```

- 定宽的block元素，利用margin进行居中

```css
.parent {
    width: 100%;
}
.child {
    width: 600px;
    height: 50px;
    margin: 0 auto;
}
```

- 定宽的block元素，利用绝对定位居中

```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    width: 100px;
    left: 50%;
    margin-left: -50px;
}
```

```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    width: 100px;
    left: 0;
    right: 0;
    margin: 0 auto;
}
```

- 不定宽的元素，利用CSS3 transform

```css
.**parent** {
    **position**: **relative**;
}
.**child** {
    **position**: **absolute**;
    **left**: 50**%**;
    **transform**: translateX(-50**%**);
}
```

- Flex 布局

```css
.parent {
    display: flex;
    justify-content: center;
}
```

- table-cell居中

```css
.parent {
    display: table-cell;
    text-align: center;
    width: 200px;
    height: 200px;
}
.child {
    width: 100px;
    height: 100px;
    display: inline-block;
}
```

### 垂直居中

- display:inline或者display: inline-block的行内元素,使用line-height

```css
.parent {
    line-height: 200px;
    height: 200px;
}
```

- 定高的block元素，利用margin进行居中

```css
.parent {
    width: 100%;
}
.child {
    width: 600px;
    height: 50px;
    margin: auto 0;
}
```

- 定高的block元素，利用绝对定位居中

```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    height: 100px;
    top: 50%;
    margin-top: -50px;
}
```

```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    width: 100px;
    top: 0;
    bottom: 0;
    margin: auto 0;
}
```

- 不定宽的元素，利用CSS3 transform

```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
}
```

- Flex 布局

```css
.parent {
    display: flex;
    align-items: center;
}
```

- table-cell居中

```css
.parent {
    display: table-cell;
    vertical-align: middle;
    width: 200px;
    height: 200px;
}
.child {
    width: 100px;
    height: 100px;
    display: inline-block;
}
```

## 多列布局

常见的多列布局，多为三列，两边宽度固定,中间自适应的布局，老点的有圣杯和双飞翼(利用浮动)，不过现在基本都是使用flex来实现。

### 圣杯布局

```html
<body class="layout">
  <div class="main">content</div>
  <div class="left">left</div>
  <div class="right">right</div>
</body>
<style>
.layout {
  min-height: 100vh;
  margin: 0;
  margin-left: 300px;
  margin-right: 200px;
}
.left {
  float: left;
  position: relative;
  margin-left: -100%;
  left: -300px;
  width: 300px;
  height: 100vh;
  background-color: antiquewhite;
}
.right {
  float: left;
  position: relative;
  right: -200px;
  width: 200px;
  height: 200px;
  margin-left: -200px;
  background-color: aquamarine;
}
.main {
  float: left;
  width: 100%;
  height: 100vh;
  background-color: bisque;
}
</style>
```

### 双飞翼

```html
<body class="layout">
  <div class="main">
    <div class="content"></div>
  </div>
  <div class="left"></div>
  <div class="right"></div>
</body>
<style>
.layout {
  min-height: 100vh;
  margin: 0;
}
.left {
  float: left;
  width: 200px;
  height: 100vh;
  margin-left: -100%;
  background-color: antiquewhite;
}
.right {
  float: right;
  width: 200px;
  height: 200px;
  margin-left: -200px;
  background-color: aquamarine;
}
.main {
  width: 100%;
  float: left;
}
.content {
  height: 100vh;
  margin-left: 200px;
  margin-right: 200px;
  background-color: bisque;
}
</style>
```

### flex布局

```html
<body class="layout">
  <div class="main">主内容栏宽度自适应</div>
  <aside class="left">侧边栏宽度固定</aside>
  <aside class="right">侧边栏宽度固定</aside>
</body>
<style>
.layout {
  display: flex;
  height: 100vh;
  margin: 0;
}

.main {
  flex: 1;
  background: #aaa;
}

.left,
.right {
  height: 100%;
}
.left {
  width: 10%;
  background: #009cff;
}

.right {
  width: 20%;
  background: orange;
}
</style>
```

### table布局

由于缺点十分明显（非语义化、布局代码冗余，灵活性差，不好维护改版，不利于SEO等）现在基本不会使用的一种布局方式，除非你要做的真的是一个table。

实现table布局我们可以直接使用table标签，或者table相关的css属性（建议无论如何都使用table的css属性，因为table中的一部分属性已被官方移除，不建议使用）

table布局，我们可以使用`display: table;`来呈现，其他的display如下所示

- `table`类似`<table>`：此元素会作为块级表格来显示，表格前后带有换行符。
- `inline-table`类似`<table>`：此元素会作为内联表格来显示，表格前后没有换行符。
- `table-header-group`类似`<thead>`：此元素会作为一个或多个行的分组来显示。
- `table-footer-group`类似`<tfoot>`：此元素会作为一个或多个行的分组来显示。
- `table-row`类似`<tr>`：此元素会作为一个表格行显示。
- `table-row-group`类似`<tbody>`：此元素会作为一个或多个行的分组来显示。
- `table-column`类似`<col>`：此元素会作为一个单元格列显示。
- `table-column-group`类似`<colgroup>`：此元素会作为一个或多个列的分组来显示。
- `table-cell`类似`<td>`和`<th>`：此元素会作为一个表格单元格显示。
- `table-caption`类似`<caption>`：此元素会作为一个表格标题显示。

table布局中由于每个cell的宽度是固定的（根据数量平均分配），这也就意味着如果你要做一个1:2:1的布局的话，不得不使用合并单元格的手段，而这个合并单元格现在无法单纯通过css实现，只能在标签上使用colspan和rowspan来实现。

### flexbox

Flexbox布局也叫Flex布局，弹性盒子布局。它的**目标**是提供一个更有效地布局、对齐方式，并且能够使父元素在子元素的大小未知或动态变化情况下仍然能够分配好子元素之间的间隙。**主要思想**是使父元素能够调整子元素的宽度、高度、排列方式，从而更好的适应可用的布局空间。设定为flex布局的元素能够放大子元素使之尽可能填充可用空间，也可以收缩子元素使之不溢出。

采用 Flex 布局的元素，称为 Flex 容器（flex container），简称"容器"。它的所有子元素自动成为容器成员，称为 Flex 项目（flex item），简称"项目"。

![https://www.ruanyifeng.com/blogimg/asset/2015/bg2015071004.png](https://www.ruanyifeng.com/blogimg/asset/2015/bg2015071004.png)

容器默认存在两根轴：水平的主轴（main axis）和垂直的交叉轴（cross axis）。主轴的开始位置（与边框的交叉点）叫做`main start`，结束位置叫做`main end`；交叉轴的开始位置叫做`cross start`，结束位置叫做`cross end`。

项目默认沿主轴排列。单个项目占据的主轴空间叫做`main size`，占据的交叉轴空间叫做`cross size`。

flex布局是现在web开发最常用的布局，基本能满足我们所有的布局需求，详细的说明建议大家可以看阮一峰大佬写的文章
[Flex 布局教程：语法篇](https://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)

以及[https://www.freecodecamp.org/chinese/news/the-ultimate-guide-to-flexbox-learning-through-examples/](https://www.freecodecamp.org/chinese/news/the-ultimate-guide-to-flexbox-learning-through-examples/) 

### Grid布局

`Grid` 布局即网格布局，是一种新的 `CSS` 布局模型，比较擅长将一个页面划分为几个主要区域，以及定义这些区域的大小、位置、层次等关系。号称是最强大的的 `CSS` 布局方案，是目前唯一一种 `CSS` 二维布局。

与flex相比，`Grid` 布局是二维布局，是将容器划分成了“行”和“列”，产生了一个个的网格，我们可以将网格元素放在与这些行和列相关的位置上，从而达到我们布局的目的。更适合整体页面框架的布局，而flex**布局是一维布局，**适合用在组件和小规模的布局中。

与table布局有点类似，同样有容器，行，列，单元格的概念，但是Grid更灵活，更强大。这里同样推荐阮一峰大佬的文章

[CSS Grid 网格布局教程](https://www.ruanyifeng.com/blog/2019/03/grid-layout-tutorial.html)
